version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Server dependencies
          command: |
            apt-get update
            apt-get install -y python3-virtualenv
      - run:
          name: Setup virtual environnement
          command: |
            virtualenv venv
            venv/bin/pip install -U pip
            venv/bin/pip install -r requirements.txt
