version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: apt-get update
      - run: apt-get install -y python3-virtualenv
      - run: virtualenv venv
      - run: venv/bin/pip install -U pip
      - run: venv/bin/pip install -r requirements.txt
