version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout # check out the code in the project directory
      - run:
        name: Install server dependencies
        command: |
          sudo apt-get update
          sudo apt-get install -y python3-virtualenv
      - run:
        name: Setup virtual environnement
        command: |
          virtualenv venv
          venv/bin/pip install -U pip
          venv/bin/pip install -r requirements.txt
