# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/server
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-virtualenv
      - run: virtualenv venv
      - run: source venv/bin/activate
      - run: pip install -U pip
      - run: pip install -r requirements.txt
